# This is a basic workflow to help you get started with Actions

name: Sftp deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  - upload:
      - name: Upload build to hosting environment
        uses: Atyn/Simple-SFTP
   # REMEMBER IMPORTANT: u have to set the ssh username, password and host but this file is public unless the entire project is private. YOU WERE ADVISED.
        with:
          url: sftp://USERNAME:PASSWORD@example.com/remote-directory
          local-directory: build-output
